[package]
name = "comic_book_reader"
version = "0.1.0"
edition = "2024"

[dependencies]
gtk = { version = "0.10.0", package = "gtk4"}
glib = "0.21.0"
walkdir = "2.5"
dirs = "6.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
